version: '3.3'

services:
  # MYSQL Database
  db:
    image: mysql:latest
    container_name: Rafaelkamil_Database_assignment2tutor
    hostname: db
    networks:
      - default
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: assignment2
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - assingnment2volume:/var/lib/mysql


# Frontend
  frontend:
    build:
      context: ./FrontEnd
    image: tutor_management_frontend
    container_name: Rafaelkamil_FrontEndContainer
    depends_on:
      - tutorcontainer
    ports: 
      - "9180:80"
    environment:
      - NGINX_PORT=80


  # Tutor Microservice

  tutorcontainer:
    depends_on:
      - db
    build:
      context: ./tutor
      dockerfile: dockerfile.tutor
    container_name: Rafaelkamil_TutorManagementContainer
    ports:
      - 9181:9181


networks:
  default: null
volumes:
  assingnment2volume: null



