FROM golang:1.16-buster AS build

WORKDIR /ProjectDocker

COPY go.mod ./

COPY go.sum ./

COPY *.go ./


RUN go build -o /tutor


FROM gcr.io/distroless/base-debian10

WORKDIR /
COPY --from=build /tutor /tutor
EXPOSE 9181
USER nonroot:nonroot
ENTRYPOINT ["/tutor"]


